shared:
  app_role_permissions:
    NOT_USED: "Effectively replaced by calls to CanCanCan."

production:
  provider_to_app:
    AD_STAFF_TECH_GRP:
      - TECHNICIAN
    AD_EXT_TERRORIST_GRP: 
      - TERRORIST

development:
  provider_to_app:
    X_STAFF_TECH_GRP: 
      - TECHNICIAN
    X_EXT_TERRORIST_GRP: 
      - TERRORIST
    0c32830c-c1cd-5685-962e-2782c65e9cf0:
      - TECHNICIAN

test:
  provider_to_app:
    X_STAFF_TECH_GRP: 
      - TECHNICIAN
    X_EXT_TERRORIST_GRP: 
      - TERRORIST
    0c32830c-c1cd-5685-962e-2782c65e9cf0:
      - TECHNICIAN
