shared:
  app_role_permissions:  # not used yet
    TECHNICIAN:
      - asset.create
      - asset.read
      - asset.update
      - asset.delete
      - asset.repair
    TERRORIST:
      - asset.sabotage

production:
  provider_to_app:
    AD_STAFF_TECH_GRP:
      - TECHNICIAN
    AD_EXT_TERRORIST_GRP: 
      - TERRORIST

development:
  provider_to_app:
    X_STAFF_TECH_GRP: 
      - TECHNICIAN
    X_EXT_TERRORIST_GRP: 
      - TERRORIST

test:
  provider_to_app:
    X_STAFF_TECH_GRP: 
      - TECHNICIAN
    X_EXT_TERRORIST_GRP: 
      - TERRORIST
