development:
  header_configs:
    Mock:
      header_extractions:
        - 
          http_header: x-auth-accesstoken
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.azure/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: get_user_template
        -
          http_header: x-auth-data
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.aws/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: mock_extract_roles
        - 
          http_header: x-auth-identity
          required: true
          extraction_function_name: nop
          validator_function_name: upn_match_to_template
      user_upn_extraction: 2
      signout_erases_session_vars: [SESS_KEY_HA_AUTH_USER, SESS_KEY_HA_AUTH_UPN, session_id]
      signout_clears_session: false
