development:
  header_configs:
    Mock:
      load_user_from_upn_function: user_from_upn
      get_upn_from_user_function: upn_from_user
      user_needs_headerauth_function: user_has_ext_authn
      create_user_from_template_function: new_user
      set_user_roles_function: set_user_roles
      header_extractions:
        - 
          http_header: x-auth-accesstoken
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.azure/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: get_user_template
        - 
          http_header: x-auth-identity
          required: true
          extraction_function_name: nop
          validator_function_name: upn_match_to_template
        -
          http_header: x-auth-data
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.aws/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: mock_extract_roles
          directory_formula: "http://127.0.0.1:3000/staticdata/$USER_memberOf.json"
      user_upn_extraction_step: 1
      signout_erases_session_vars: [SESS_KEY_HA_AUTH_USER, SESS_KEY_HA_AUTH_UPN, warden.user.user.key] # , session_id
      signout_clears_session: false
      return_auth_method_header: true

test:
  header_configs:
    Mock:
      load_user_from_upn_function: user_from_upn
      get_upn_from_user_function: upn_from_user
      user_needs_headerauth_function: user_has_ext_authn
      create_user_from_template_function: new_user
      set_user_roles_function: set_user_roles
      header_extractions:
        - 
          http_header: x-auth-accesstoken
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.azure/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: get_user_template
        - 
          http_header: x-auth-identity
          required: true
          extraction_function_name: nop
          validator_function_name: upn_match_to_template
        -
          http_header: x-auth-data
          required: true
          get_signing_key: mock_key
          signing_key_args: [ "www.aws/PKCS/%kid%/key.gpg" ]
          sig_verifier: mock_sig_validation
          extraction_function_name: mock_extract_roles
          directory_formula: "file:./public/staticdata/$USER_memberOf.json"
      user_upn_extraction_step: 1
      signout_erases_session_vars: [SESS_KEY_HA_AUTH_USER, SESS_KEY_HA_AUTH_UPN, warden.user.user.key] # , session_id
      signout_clears_session: false
      return_auth_method_header: true
