development:
  header_configs:
    user2:
      set_on_intercepted_path: /MOCKPROXY/user2
      remove_on_intercepted_path: /MOCKPROXY/scrub
      header_values:
        x-auth-accesstoken: 1002
        x-auth-identity: user2@example.com
        x-auth-data: {name: "User McTwo", memberOf: [ "X_STAFF_TECH_GRP", "X_SOMETHING_ELSE" ], mail: "user2@example.com" }
    user3:
      set_on_intercepted_path: /MOCKPROXY/user3
      remove_on_intercepted_path: /MOCKPROXY/scrub
      header_values:
        x-auth-accesstoken: 1003
        x-auth-identity: user3@example.com
        x-auth-data: {name: "Terry Wrist", memberOf: [ "X_EXT_TERRORIST_GRP", "X_SOMETHING_ELSE" ], mail: "user3@example.com" }
